### PR TITLE
6.0 preview playground

### PR DESCRIPTION
**Pull request by droserasprout**

### CODE REVIEW

**Comment by Zir0h** [comment]
Nice! I only had to do this to get it running:

```
diff --git a/src/hicdex/models.py b/src/hicdex/models.py
index 2946711..d88628d 100644
--- a/src/hicdex/models.py
+++ b/src/hicdex/models.py
@@ -1,7 +1,8 @@
 from datetime import datetime
 from enum import Enum, IntEnum
 
-from tortoise import ForeignKeyFieldInstance, Model, fields
+from tortoise import ForeignKeyFieldInstance, fields
+from dipdup.models import Model
 
 
 class SwapStatus(IntEnum):
```

**Comment by droserasprout** [comment]
Nice! I'm going to release `6.0.0-rc1` in the next couple of days to make things official. No other changes in SDK logic are expected. Could you spin up this branch on your server? You can leave Sentry DSN as is for me to timely fix issues, if any.

**Comment by Zir0h** [comment]
Hi! Can this be merged now that v6 is out? I didn't see any issues on my end.

**Comment by droserasprout** [comment]
Sure. The only changes left in this branch are more strict typechecking and CI checks.

**Comment by Zir0h** [comment]
Thank you so much!

**Pull request merged**
